language: node_js

node_js:
  - 8.5.0

sudo: required

services:
  - docker

dist: trusty

cache:
  directories:
    - node_modules

before_install:
  - cp makefile.docker makefile

before_script:
  - make install

script:
  - make test
