version: '3'
services:
  gatsby:
    image: node:8-alpine
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8000:8000
    command: npm run develop
  storybook:
    image: node:8-alpine
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 9001:9001
    command: npm run storybook
